db:
   image: mysql
   container_name: bbdd
   ports:
      - "4306:3306"
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
   volumes:
      - ./data:/var/lib/mysql
